### ISSUE TITLE
Issues creating reference

### ISSUE THREAD

**Issue by tomasgodoicd** [glutanimate/internal-references#1]
I've created a reference, but it creates a link pointing to the collection folder, like so:
`
<a href="file:///F%3A/AnkiHny/Hny/collection.media/" class="ilink" data-a="eyJzcmMiOiAiY2lkOjE1MDUwOTMxMTMzNjkiLCAiaGx0IjogIlx1NjYwZVx1NjVlNVx1NTNjOFx1NTkyOVx1NmRhZiIsICJkbGciOiAicHJldmlldyJ9" data-cid="1505093113369">明日又天涯</a>
`
My Anki version is 2.0.36

**Comment by glutanimate** [comment]
Not sure what's going on there. Could you give the add-on a try on a more recent Anki release (2.0.47 preferably) and let me know if it works? Specifically, could you look at the field HTML directly after inserting a link and see what it looks like at that point?

This is what the links look like on my end:

    <a href="" class="ilink" data-a="eyJzcmMiOiAibWlkOjE0ODE5MjQyNjkwODkiLCAiaGx0IjogIiIsICJkbGciOiAiYnJvd3NlIn0=" onclick='py.link("ilink:" + this.dataset.a); return false;'>asdf</a>

Note the empty `href` and the `onclick` attribute. My initial suspicion is that Anki might be swallowing these up when processing your field contents.

The difference in behaviour could either be due to different Anki versions or different platforms. What OS are you using Anki on? I've only tested the add-on on Linux and Windows.

**Comment by tomasgodoicd** [comment]
I've tried on the 2.0.47 version with mock cards and it worked just fine. There's only a little problem I've found...
When you click on the link from the preview Window it will try to open it through the OS.

**Comment by glutanimate** [comment]
That's strange. Could you post the HTML code of the links that are being opened through the OS by any chance?

**Comment by tomasgodoicd** [comment]
My OS is Windows 10.
`
我爱你<div><a href="" class="ilink" data-a="eyJzcmMiOiAiY2lkOjE1MDUwOTMxMTMzNjkiLCAiaGx0IjogIiIsICJkbGciOiAicHJldmlldyJ9" data-cid="1505093113369" onclick='py.link("ilink:" + this.dataset.a); return false;'>天涯</a></div><div><br /></div>
`
From the review window it works just fine. The problem only happens when on preview.

**Comment by glutanimate** [comment]
Ah, I see now. Previewer support is limited to the Advanced Preview add-on since Anki itself does not support custom link handlers in its preview window. I will add the required dependencies to the documentation once I release the add-on on AnkiWeb. Thanks for the reminder!

Glad to hear the links are working otherwise! Closing this for now.
